#!/bin/sh

echo "############### PLEASE, INSTALL SDRPLAY DRIVERS ###############"
echo "#####                                                     #####"
echo "##### This package will not work without SDRPlay drivers, #####"
echo "##### which have to be installed separately. Please,      #####"
echo "##### download these drivers from                         #####"
echo "#####                                                     #####"
echo "#####     https://www.sdrplay.com/downloads/              #####"
echo "#####                                                     #####"
echo "###############################################################"

exit 0
